### ISSUE TITLE
Repository Feedback

### ISSUE THREAD

**Issue by go-christianharrel** [PUP-BSIT/ex9-tuf_developers#6]
### Required:
- [x] **Remove .otf Extension from index_elements File**
  - Kindly remove the .otf extension from the `index_elements` file. Also, ensure to maintain neat and organized personal folders. ([Issue #10 from your past exercise](https://github.com/PUP-BSIT/ex7-tuf_developers/issues/10))

- [x] **Include @cahigan-marklouie in README**
  - Cahigan Marklouie is not currently listed in the README file. Please ensure their inclusion.

- [x] **Commit Message Consistency**
  - Please maintain consistency in commit messages, ensuring clarity and conciseness. ([Refer to this Guideline](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit?fbclid=IwAR1pphsWlliw0L_vbPJKbRCpW81Gt151vhOUq4iEw0Ftms7GjjedbKMX-fI_aem_AaHDPId1LpnIKTLO8jtJYQQGefS9ZBVU9dr1OCxS88dCO9DgcNB0UTMObNs4Ok6LM47wdHt4CyLzGnWZQJ0fiCb9#slide=id.g28d48e53e08_0_21))
---
### Recommendations:
Consider the following suggestions for improving your GitHub workflow:

1. **Pull Request Integration for Collaboration**
   - Enhance collaboration and streamline code review by utilizing pull requests for proposed changes. Consider incorporating a branch or pull request workflow to address and close assigned issues for each team member. ([Check out this guide](https://docs.google.com/presentation/d/1IuvwLGgfo-7G_-PW-QlGmFnX9VE6SqUKVUr5JfCfH1A/edit#slide=id.g29921b43961_1_27))

2. **Inspect Resource Tool**
   - Take advantage of the inspect resource feature for comprehensive code examination and debugging. ([Inspect Resource](https://www.inspectresource.com/#/tools))

3. **Prettier Integration**
   - Improve code formatting consistency and readability by integrating Prettier into your development workflow. While Prettier helps adhere to coding guidelines, it's advisable to perform manual checks to ensure accuracy. ([Install Prettier for VSCode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode))

4. **JSON Line Limit**
   - Enhance maintainability and readability by adhering to the 80-line limit for JSON files, following basic coding guideline. ([Refer to this Guideline](https://docs.google.com/presentation/d/1iCoz17mBxZtIQ9PifAW0jjKsuv4xDTlx-TPQxdLySow/edit#slide=id.g24da8de92d7_0_0))

   Instructions:
   1. Press `Ctrl + ,` to open settings.
   2. Navigate to "Open Settings (JSON)".
      ![image](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/51312012/9dae692e-8919-4a2f-96d7-b1e0dff67b03)
   3. Add the following line: `"editor.rulers": [80]`.

Implementing this guideline will enhance the clarity and organization of JSON files, contributing to better code maintenance and readability.

---
### Team Index Enhancement:

![Team Index](https://github.com/PUP-BSIT/ex9-tuf_developers/assets/51312012/53cef210-bd46-4016-8767-0d3220dfc0ae)

Here's a snippet of the CSS code for your reference:

```css
/* MY CSS FOR THE INDEX PAGE */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  background-color: #221815;
  font-family: "ITC";
  font-size: 20px;
  animation: fadeIn 10s forwards;
}

img {
  width: 15rem;
  height: 20rem;
}

h1 {
  color: #fbc649;
  font-size: 5rem;
}

a,
a:link,
li {
  color: #fbc649;
  font-size: 2rem;
}

@font-face {
  font-family: "ITC";
  src: url("ITC Machine Medium.otf");
}

@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  flex-direction: column;
}
```
Feel free to adjust and customize the styles as needed to fit your project requirements and preferences. 

---

Your attention to these matters is greatly appreciated. Your code and repository reflect a commendable standard, demonstrating your commitment to excellence. **Keep up the outstanding work!** 

Please take note of the feedback provided by your reviewers to further refine this exercise and enhance its quality. Continue striving for excellence by incorporating the suggestions from your reviewers and optimizing your workflow for improved collaboration.

Apologies for the delayed GitHub issue and thank you for your patience and cooperation throughout this process. If you have any questions or need further assistance, please don't hesitate to ask! :heartpulse:
